abstract: For when your code no worky
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: worky
no_index: 
  directory: 
    - inc
    - t
requires: 
  orz: 0.12
  perl: 5.6.1
version: 0.10
